{
 "title": "Luftqualität",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bme_location",
    "label": "Sensor",
    "query": {
     "query": "label_values(bsec_uptime_sec, location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Luftfeuchte",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "bsec_compensated_humidity{location=\"$bme_location\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "bsec_compensated_temp{location=\"$bme_location\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "0.01*bsec_raw_pressure{location=\"$bme_location\"}",
     "legendFormat": "Rohdaten"
    },
    {
     "expr": "((0.01*bsec_raw_pressure{location=\"$bme_location\"}) * (1.0 - ((0.0065*186.0) / (bsec_compensated_temp{location=\"$bme_location\"} + (0.0065 * 186.0) + 273.15)))^-5.257 )\n",
     "legendFormat": "Kompensiert"
    }
   ]
  },
  {
   "title": "Luftqualität [IAQ]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bsec_static_iaq{location=\"$bme_location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bsec_co2_equiv{location=\"$bme_location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "gauge",
   "description": "Recommended Exposure\ngreen: no limit,\nyellow: < 12 months, \norange: < 1 month, \nred: hours",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bsec_breath_voc_equiv{location=\"$bme_location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "stat",
   "description": "Lüften wenn außen < innen",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(243.04 * (ln(bsec_compensated_humidity / 100) + (17.625 * bsec_compensated_temp / (243.04 + bsec_compensated_temp)))) / (17.625 - (ln(bsec_compensated_humidity / 100) + (17.625 * bsec_compensated_temp / (243.04 + bsec_compensated_temp))))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Messgenauigkeit",
   "type": "snuids-trafficlights-panel",
   "description": "0=initializing, 1=unstable, 2=recalibrating, 3=stable",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "bsec_iaq_accuracy{location=\"$bme_location\"}",
     "legendFormat": "IAQ Accuracy"
    }
   ]
  }
 ]
}